### ISSUE TITLE
[TEST] Add in depth latency information of the Runtime system

### ISSUE THREAD

**Issue by DanielMolina24** [pioneers/runtime#165]
This would be useful for debugging any parts that seem to act slower than others for some odd reason. At every runtime process, we would like to attach a timestamp that shows how long it took to get to that process. The ideal chain would be:
1. `Dawn` sends a proto-buf
2. `Net Handler` receives photo but and writes `TIMESTAMP A` to `Shared Memory`
3. `Executor` reads `TIMESTAMP A`. Writes `TIMESTAMP B` to `Shared Memory`
4. `Dev Handler` reads `TIMESTAMP B`. Writes `TIMESTAMP C` to `Shared Memory`
5. `Executor` reads `TIMESTAMP C`. Writes `TIMESTAMP D` to `Shared Memory`
6. `Net Handler ` reads `TIMESTAMP D`. Writes `TIMESTAMP B` to the protobuf and sends it back to `Dawn`

It might help to create a "Time" Device with these different `TIMESTAMP` parameters

**Comment by benliao1** [comment]
Will close this issue, in favor of #195
