### ISSUE TITLE
[NET_HANDLER] send_log_msg isn't always called after a log statement

### ISSUE THREAD

**Issue by AVSurfer123** [pioneers/runtime#177]
Tested this by printing something from `send_log_msg` and sometimes it wouldn't show up after logs, even though another process logged something with level at INFO or higher. Don't know what the cause is yet

**Comment by levincent06** [comment]
Leaving a note here to try to reproduce this issue after #194 gets merged in, as the PR has some fixes to net handler that may resolve the issue.

**Comment by benliao1** [comment]
Closing for now, this has probably been fixed by adding a buffer on Dawn's end when receiving data from Runtime.
