### ISSUE TITLE
[BUILD] Add bash autocomplete to runtime script

### ISSUE THREAD

**Issue by AVSurfer123** [pioneers/runtime#178]
Here is a tutorial on bash completion: https://iridakos.com/programming/2018/03/01/bash-programmable-completion-tutorial.
Just would need to add `complete -W "run build test format" runtime` to `.bashrc` or something that gets sourced. 
However this would add another step during installation. Maybe the first time you run `runtime`, it will automatically add this line to a file in `/etc/bash_completion.d/`.

**Comment by benliao1** [comment]
Will mark as `wontfix` because while it would be nice, I don't think we will ever realistically implement this.
