### ISSUE TITLE
[MISC] Create a web UI for all active robots

### ISSUE THREAD

**Issue by levincent06** [pioneers/runtime#219]
The shared memory UI has proven to be very useful to debug Runtime during development and in production :P 
For in-person competitions, we're imagining a computer can open a webpage that displays shm-ui-like information for every active robot.

Additional features of the UI will be added to this GitHub issue as we consider more.

**Comment by benliao1** [comment]
This might not be necessary any more if we implement Runtime Status... most of the time we only care about the things that will be in the Runtime Status message during competition.

**Comment by benliao1** [comment]
As stated above, probably won't be implemented, so closing with wontfix label....
