### ISSUE TITLE
[MISC] Create a lowcar submodule

### ISSUE THREAD

**Issue by DanielMolina24** [pioneers/runtime#225]
In order to make it easy for Runtime and Shepherd to share changes in lowcar files and device implementations, it would be good to turn lowcar into a submodule. 
This would include(stealing @levincent06 list lol): 

- General lowcar files (Device.*, Messenger.*, defs.h)
- Device implementations (LineFollower, KoalaBear, Shepherd devices (I think they just call them Device1 or something)
- Flash script
- Dev handler

Some things that first need investigation would be:
- Modifying the flash scripts since currently it only symlinks the Runtime(or Shepherd devices) device libraries rather than both. Most likely will be a small-ish change within flash.sh
- Making sure that we can compile code that is device specific so as to avoid having repeats of code or needing to change the device specific code often. This seems like a good avenue for exploring: https://forum.arduino.cc/t/determining-which-board-type-is-being-used/111247

**Comment by benliao1** [comment]
Since Shepherd now uses their own sensors framework, it is no longer necessary for us to make lowcar a submodule of Runtime / make a separate repo for it. Will close!
