### ISSUE TITLE
Shared Memory UI bug

### ISSUE THREAD

**Issue by DanielMolina24** [pioneers/runtime#252]
There were times, when starting up the shared memory UI, where it would have a glitchy appearance. This would not resolve with just rebuilding the shared memory UI. This required rebuilding Runtime as a whole and rebooting the PiE. This may mean it is an issue with Shm itself which causes the UI to freak out.

**Comment by benliao1** [comment]
Unless we somehow find a way to reproduce this issue, I don't think we're ever going to be able to fix this issue. Maybe it will fix itself once we figure out how to make shared memory stop dying sporadically. Will mark as `wontfix` and close for potentially forever....
