### ISSUE TITLE
[LOWCAR] Making INT params be int32_t instead of int16_t

### ISSUE THREAD

**Issue by AVSurfer123** [pioneers/runtime#81]
Also, when testing the lowcar devices, update the parameters in `runtime_util.c` to be more accurate.

**Comment by benliao1** [comment]
`lowcar` changes to support this will be made in `lowcar_testing` branch by me. `dev_handler` changes to support this will be made in `dev_handler_cli` branch by @levincent06 and @DanielMolina24
