### ISSUE TITLE
[TEST] Rewrite test.c in Cython and integration tests in Python

### ISSUE THREAD

**Issue by AVSurfer123** [pioneers/runtime#90]
The test framework checking would be much nicer if the tests and outputs were written in Python and we check these outputs with the results from calling the C test clients.

**Comment by benliao1** [comment]
Is related to issue #78

**Comment by benliao1** [comment]
Would have been fixed by #101 but that PR was overridden by work during Fa '20 semester by @0neDividedbyZer0 , @levincent06 , and @DanielMolina24 !
