### ISSUE TITLE
[MISC] Convert all signal to sigaction

### ISSUE THREAD

**Issue by AVSurfer123** [pioneers/runtime#95]
According to the `signal` man page (https://man7.org/linux/man-pages/man2/signal.2.html), we should avoid using `signal` and instead use `sigaction`.

**Comment by benliao1** [comment]
If we do this, we need to update the wiki page on signals as well (https://github.com/pioneers/c-runtime/wiki/Signals)

**Comment by benliao1** [comment]
Wontfix because we are only working on one version of linux and `signal()` has been working for us thus far.
