### ISSUE TITLE
[TESTS] Convert the virtual devices to use threads instead of processes

### ISSUE THREAD

**Issue by AVSurfer123** [pioneers/runtime#99]

**Comment by benliao1** [comment]
We made some changes / bug fixes to the virtual devices and `dev_handler` early in the semester and general fixes and rewrites of the test framework that gradually fixed this issue (which was related to virtual devices disconnecting or leaving sockets open after disconnecting for no reason). Result is that we think issue is resolved and decided not to pursue this change. Marking as wontfix.
